export default [
    'alipay',
    'bancontact',
    'eps',
    'ideal',
    'klarna',
    'postfinance_card',
    'postfinance_efinance',
    'paypal',
    'prepayment',
    'przelewy24',
    'twint',
    'wechatpay',
    'wero',
];